#!/usr/bin/env python3
# Copyright Anton Semjonov, Licensed under GPL-3.0

from keyconvert.opensshkey import OpenSSHKey
from keyconvert.arguments import args

key = OpenSSHKey()

if args.json:
  print(key.toJSON())

if args.dir != None:
  key.write(args.dir)