#!/usr/bin/env python3

"""Convert armored OpenSSH key to binary TinySSH format."""

from keyconvert.arguments import Arguments
from keyconvert.opensshkey import OpenSSHKey

args = Arguments()
key = OpenSSHKey(args.key)

print(key.toJSON())
